### ISSUE TITLE
'JudgeAgent' object has no attribute 'get_evidence'

### ISSUE THREAD

**Issue by lsm1103** [metauto-ai/agent-as-a-judge#9]
PYTHONPATH=. python scripts/run_ask.py \
  --workspace $(pwd)/benchmark/workspaces/OpenHands/39_Drug_Response_Prediction_SVM_GDSC_ML \
  --question "What does this workspace contain?"

```shell
Traceback (most recent call last):
  File "/home/ecs-user/deploy/agent-as-a-judge/scripts/run_ask.py", line 130, in <module>
    main(
  File "/home/ecs-user/deploy/agent-as-a-judge/scripts/run_ask.py", line 32, in main
    handle_question(judge_agent, initial_question, logger)
  File "/home/ecs-user/deploy/agent-as-a-judge/scripts/run_ask.py", line 44, in handle_question
    response = judge_agent.ask_anything(question)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ecs-user/deploy/agent-as-a-judge/agent_as_a_judge/agent.py", line 222, in ask_anything
    llm_stats, start_time = self.get_evidence(
                            ^^^^^^^^^^^^^^^^^
AttributeError: 'JudgeAgent' object has no attribute 'get_evidence'
```

This method doesn't seem to have been implemented？
![image](https://github.com/user-attachments/assets/6c46bc03-4323-4d28-b280-24c1b35e5e78)

**Comment by mczhuge** [comment]
Dear @lsm1103 , 

Thank you! We have solved it by https://github.com/metauto-ai/agent-as-a-judge/pull/10

Authors of AaaJ
